### ISSUE TITLE
brotli.error: BrotliDecompress failed

### ISSUE THREAD

**Issue by hufenglin** [HACHp1/chptrans#1]
安装好后使用会报ModuleNotFoundError: No module named 'win32clipboard'

然后我就安装了：
 pip install pywin32

然后再次使用好像成功了：
Desktop\chptrans-master> chptrans

***************************************************************************************
        欢迎使用 CHP's translator
        用法：
            复制想翻译的英文（ctrl+c)，复制完后按f键翻译（翻译器会将剪切板中的内容翻译为中文）
        感谢：
            感谢Bing的接口
***************************************************************************************

当按CTL+C 再按F 时候 报错：
brotli.error: BrotliDecompress failed

难道是python 版本不对吗？

**Comment by HACHp1** [comment]
> 
> 
> 安装好后使用会报ModuleNotFoundError: No module named 'win32clipboard'
> 
> 然后我就安装了：
> pip install pywin32
> 
> 然后再次使用好像成功了：
> Desktop\chptrans-master> chptrans
> 
> ```
>     欢迎使用 CHP's translator
>     用法：
>         复制想翻译的英文（ctrl+c)，复制完后按f键翻译（翻译器会将剪切板中的内容翻译为中文）
>     感谢：
>         感谢Bing的接口
> ```
> 
> 当按CTL+C 再按F 时候 报错：
> brotli.error: BrotliDecompress failed
> 
> 难道是python 版本不对吗？

已修正，现在再试试呢
